# Description.
# Made by Ryu Eojin, Institue of Technology, Platform Department.

# Provide authorization for the "manager pod" to handle kubernetes resources inside the container.
# You should create 3 resources in the following order.
# 1) ClusterRole
# 2) ServiceAccount
# 3) ClusterRoleBinding
# It should be created "In advance", "Only one time" for each cluster.

apiVersion: v1
kind: ServiceAccount
metadata:
  name: distributetrain-serviceaccount
  # Should specify the namespace. If you want others.
  namespace: default
