# Description. 
# Made by Ryu Eojin, Institue of Technology, Platform Department. 
 
# Provide authorization for the "manager pod" to handle kubernetes resources inside the container. 
# You should create 3 resources in the following order. 
# 1) ClusterRole 
# 2) ServiceAccount 
# 3) ClusterRoleBinding 
# It should be created "In advance", "Only one time" for each cluster. 
 
apiVersion: rbac.authorization.k8s.io/v1 
kind: ClusterRole 
metadata: 
  name: distributetrain-clusterrole 
rules: 
  # Manager pod should be able to look up, create, and delete worker pod.  
- apiGroups: [""] 
  resources: ["pods"] 
  verbs: ["create", "list", "delete", "get"] 
 
  # Manager pod should be able to look up nodes. 
- apiGroups: [""] 
  resources: ["nodes"] 
  verbs: ["list", "get"]
